### ISSUE TITLE
Some suggestions : add some useful function and more

### ISSUE THREAD

**Issue by shawnye** [munificent/wren#490] opened 2017-12-05 17:13 UTC
Just learn wren and like it,  and try to write csv parser,
 some  sugguestion without  careful thought:

- String class add `trim() ` .
- File class add `iterateLine()` : iterate big file line by line.
- add simple regex support?
- add +=, -= series operator
- support function assignment like `var pl = System.print `

**Comment by KyleCharters** [comment] 2017-12-05 20:10
1. trim() sounds useful. +1
2. `File.read("file.txt").split("\n")` is fairly close, however we could probably get a performance boost if we read line by line directly in c...
3. Sounds like it would be a good fit for an optional class.
4. Do you propose adding it as additional operator? Or sugar that expands to `x = x + y`? For the latter, would it work with other operators? `x >>= y`?
5. I don't see this working with the current system. What (I think) you suggested, `System.print` (without any parenthesis) would be a pointer to a function, however this can be confused with getters. I think its best if we leave this one out, and just wrap it with a function.

**Comment by shawnye** [comment] 2017-12-06 23:41
more suggestion for Directory  class:
- makeDir() , make new dir and auto make parent dir if not exists
- deleteDir(),

**Comment by shawnye** [comment] 2017-12-07 16:06
My workaround for  `return s[i..j]` :
<pre>
var sb = []
        var k = 0
        for(v in s){
            if(k >= i && k <= j){
                sb.add(v)
            }

            k = k+1
        }

        return sb.join()
</pre>

**Comment by minirop** [comment] 2017-12-07 18:23
the String class does not accept Ranges for it's subscript operator (as Python does), only integers.

I found [this comment](https://github.com/munificent/wren/issues/2#issuecomment-32513128) but I don't think anything moved since.

**Comment by KyleCharters** [comment] 2017-12-07 18:51
Actually, It looks like [subscript ranges are supported](https://github.com/munificent/wren/blob/c4d08bcb81045f471ff182d48f0a3de353fc0f46/src/vm/wren_core.c#L1043-L1066). I believe the issue is that [StringCodePointSequence](https://github.com/munificent/wren/blob/c4d08bcb81045f471ff182d48f0a3de353fc0f46/src/vm/wren_core.wren#L264-L274) doesn't support ranges. We should fix this for the sake of consistency.

**Comment by underscorediscovery** [comment] 2017-12-07 19:48
For trim I imagined it being native, but for a wren version, I wouldn't put the string constants like `" "` inside of the while loops, it could generate a lot of garbage. making them a variable first is 1 local, or you could use a module variable like:
```
var NL_ = "\n"
class Str {
  ...  if(s[j] == NL) ... 
}

**Comment by munificent** [comment] 2018-04-29 00:00
I definitely like some of these, though lumping them all into one big issue makes it hard to track them. Would you mind filing separate issues for them, please?

> I wouldn't put the string constants like " " inside of the while loops, it could generate a lot of garbage.

No, that won't make a difference. If it's a string literal, it is stored in the function's constant table. "Executing" the string literal expression just loads the constant onto the stack. There's no allocation going on.

Of course, an *expression that evaluates to a string* might be worth hoisting out for performance. But a simple bare string literal is fine.

**Comment by munificent** [comment] 2018-04-29 00:03
> support function assignment like var pl = System.print

This would be handy, but it clashes with Wren's notion of overloading and arity. There are actually two methods named "print" on System, `System.print()` and `System.print(object)`. Those are totally distinct methods as far as Wren is concerned, so if you wanted to get "a function for 'print'", it's not clear which one it should return.

We could try to synthesize a single function that can call either based on the number of arguments you pass it, but that feels like it goes against the grain of the language to me. I think a better solution would be one where you specify which of the overloads you want... but that gets into more interesting syntax challenges. At that point, you're probably just better off making a little lambda yourself.

**Comment by munificent** [comment] 2018-07-15 17:51
OK, I added trim methods on String. There are already issues for some of the other requests here:

* Self-assignment operators: #539
* Regex: #120

I'm not sure about iterating over a file by line yet. If we want to do that, it would be good to have a separate tracking bug. I'm closing this out. :)

**Closed by munificent** 2018-07-15 17:51 UTC
Labels: core, enhancement, language
