### ISSUE TITLE
Question: How to handle imports with subdirectories

### ISSUE THREAD

**Issue by maxdeviant** [munificent/wren#501] opened 2018-01-18 05:40 UTC
I'm running into an issue with resolving imports when using a directory structure with subdirectories.

I have two files in a parent directory (`src`), and then a test file in `__tests__`, which is a subdirectory of `src`.

```c
// src/shared.wren
class Shared {
  static world { "world" }
}

// src/greeter.wren
import "shared" for Shared

class Greeter {
  static hello() {
    return "Hello, " + Shared.world
  }
}

// src/__tests__/greeter.test.wren
import "../greeter" for Greeter

System.print(Greeter.hello())
```

Running `wren src/__tests__/greeter.test.wren` results in Wren complaining that it can't find the module `'shared'`:

```
Could not load module 'shared'.
[../greeter line 1] in (script)
```

Changing the import to the following causes the test to work, because the import is now correct relative to the `greeter.test.wren` file:

```c
// src/greeter.wren
import "../shared" for Shared
```

However, this means that the import will no longer work when calling from a different context (e.g., a sibling file to `greeter.wren`.

Is there a way to make the imports relative to the file they are called from rather than the main module?

**Comment by maxdeviant** [comment] 2018-01-18 05:53
Looks like the proposal in #479 covers this.

**Comment by heyitsmeuralex** [comment] 2018-01-18 11:16
@maxdeviant I'm almost certain #479 _doesn't_ specifically cover this. That issue is about non-relative imports so you can download new modules to, say, `~/.wren/modules/`.

This looks like a bug, or at least a misfeature, to me!

**Comment by minirop** [comment] 2018-01-18 14:13
_it's not a bug, it's a feature._

The thing is the CLI look up files from the current working directory, and since it never knows from where the files are loaded from, it can't adapt `import` inside imported files.

**Comment by maxdeviant** [comment] 2018-01-18 15:10
@heyitsmeuralex I was going off the situation described in the ["Relative Imports"](https://github.com/munificent/wren/blob/9f79dfcdac466c1198cecedd12fc857d6e62bc36/doc/rfc/0001-smarter-imports.md#relative-imports) section of the proposal, which is the same scenario as what I ran into.

**Comment by munificent** [comment] 2018-07-16 14:49
With the latest code in the CLI, you can now do relative imports. If you change your code to:

```
// src/shared.wren
class Shared {
  static world { "world" }
}

// src/greeter.wren
import "./shared" for Shared // <- "./" here to make it relative.

class Greeter {
  static hello() {
    return "Hello, " + Shared.world
  }
}

// src/__tests__/greeter.test.wren
import "../greeter" for Greeter

System.print(Greeter.hello())
```

Then it *should* work. The import stuff is very new, though, so there are probably some issues to shake out. Closing this now optimistically. :)

**Closed by munificent** 2018-07-16 14:49 UTC
