### ISSUE TITLE
Wren function refuses to execute from native invoking

### ISSUE THREAD

**Issue by paladin-t** [munificent/wren#580] opened 2018-07-12 05:22 UTC
Environment: Win7 64bit, VC++2015
Revision: latest master

The `A.bar()` function refuses to execute from native invoking by `foreign foo()`, generates error and crashes:

```
Error
  Ln: -1
  Message: Fn does not implement 'bar()'.
Error
  Ln: -33686019
  Module: main
  Message: test()
Error
  Ln: 10
  Module: main
  Message: (script)
```

![crash](https://user-images.githubusercontent.com/2062224/42613964-3da69a04-85d6-11e8-99e3-efc2273699dc.png)

Can be reproduced with the follow code:

```c
#include "wren.hpp"
#include <stdio.h>
#include <sstream>

static const char* const code =
	"class A {\n"
	"	static test() {\n"
	"		A.foo()\n"
	"	}\n"
	"	foreign static foo()\n"
	"	static bar() {\n"
	"		System.print(\"Oops...\")\n"
	"	}\n"
	"}\n"
	"A.test()\n"; // <--- (b)

static void foo_impl(WrenVM* vm) {
	wrenEnsureSlots(vm, 1);
	wrenGetVariable(vm, "main", "A", 0);
	WrenHandle* klass = wrenGetSlotHandle(vm, 0);
	WrenHandle* method = wrenMakeCallHandle(vm, "bar()");

	wrenEnsureSlots(vm, 1);
	wrenSetSlotHandle(vm, 0, klass);

	wrenCall(vm, method);

	wrenReleaseHandle(vm, method);
	wrenReleaseHandle(vm, klass);
}

static WrenForeignMethodFn on_bind_foreign_method(WrenVM* vm, const char* module, const char* className, bool isStatic, const char* signature) {
	if (strcmp(module, "main") == 0) {
		if (strcmp(className, "A") == 0 && strcmp(signature, "foo()") == 0 && isStatic) {
			return foo_impl;
		}
	}

	return nullptr;
}

static void on_write(WrenVM* vm, const char* text) {
	printf("%s", text);
}

static void on_error(WrenVM* vm, WrenErrorType type, const char* module, int line, const char* message) {
	std::stringstream head, msg;
	switch (type) {
	case WREN_ERROR_COMPILE: head << "Compile error"; break;
	case WREN_ERROR_RUNTIME: head << "Runtime error"; break;
	case WREN_ERROR_STACK_TRACE: head << "Stack trace error"; break;
	}

	msg << "Error\n";
	msg << "  Ln: " << line << std::endl;
	if (module)
		msg << "  Module: " << module << std::endl;
	if (message)
		msg << "  Message: " << message << std::endl;

	std::string txt = msg.str();
	on_write(vm, txt.c_str());
}

int main() {
	WrenConfiguration cfg;
	wrenInitConfiguration(&cfg);
	cfg.bindForeignMethodFn = on_bind_foreign_method;
	cfg.writeFn = on_write;
	cfg.errorFn = on_error;
	WrenVM* vm = wrenNewVM(&cfg);

	WrenInterpretResult ret = wrenInterpret(vm, code);
	if (ret != WREN_RESULT_SUCCESS)
		fprintf(stderr, "Interpreter error.\n");
	//foo_impl(vm); // <--- (a)

	wrenFreeVM(vm);

	return 0;
}
```

However, when I uncomment (a), and comment (b), the program runs fine. Am I missing anything?

I'm new to Wren, sorry if I'm asking a silly question.

**Comment by underscorediscovery** [comment] 2018-07-12 05:40
There should be an error that you can't call our from a foreign function. 
https://github.com/munificent/wren/blob/master/src/vm/wren_vm.c#L1357
Maybe it's not hitting that somehow, but:

c calls wren ->
wren calls c ->
not allowed to call wren again. 

The vm is not currently reentrant.

**Comment by paladin-t** [comment] 2018-07-12 06:36
Thanks for the quick reply. It didn't hit that. Will there be reenterable in future?

**Comment by bjorn** [comment] 2018-07-12 14:25
> Thanks for the quick reply. It didn't hit that.

Then you probably compiled Wren in release mode, since those are not errors but asserts.

**Comment by paladin-t** [comment] 2018-07-12 15:14
Thanks but it’s in debug mode, I know assertions

**Comment by bjorn** [comment] 2018-07-12 16:03
> Thanks but it’s in debug mode, I know assertions

Did you check whether that code actually gets executed? I'm wondering about it because in your screenshot, it's showing "current" being NULL, but if it was then the ASSERT line above would have already crashed by null-pointer-dereference when trying to check the value of `vm->fiber->error`.

**Comment by munificent** [comment] 2018-07-16 14:13
Closing this as a duplicate of #487. Yes, I do think we need to handle some amount of re-enterability. Now that I've got a first pass at the relative import stuff landed on master, I'm hoping to look into it soon.

**Closed by munificent** 2018-07-16 14:13 UTC
Labels: duplicate
